# Generated by Django 2.2.5 on 2020-03-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='status',
        ),
        migrations.AddField(
            model_name='magazine',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
