# Generated by Django 2.2.5 on 2020-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200319_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
