# Generated by Django 2.2.5 on 2020-03-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200325_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
