# Generated by Django 2.2.5 on 2020-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200324_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedmagazine',
            name='isReturned',
        ),
        migrations.AddField(
            model_name='borrowedmagazine',
            name='status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
