# Generated by Django 2.2.5 on 2020-03-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20200325_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetArticle',
        ),
    ]
