# Generated by Django 2.2.5 on 2020-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_delete_getarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
