# Generated by Django 2.2.5 on 2020-03-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_auto_20200321_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='borrowed_timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
