# Generated by Django 2.2.5 on 2020-03-21 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0009_auto_20200322_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrowed',
            new_name='BorrowedBook',
        ),
    ]
