# Generated by Django 2.2.5 on 2020-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_auto_20200322_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='isReturned',
            field=models.BooleanField(default=False),
        ),
    ]
