# Generated by Django 2.2.5 on 2020-03-22 11:07

import datetime
from django.db import migrations, models
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_borrowedbook_isreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='deadline',
            field=models.DateField(default=library_app.models.get_deadline),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_timestamp',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
